version: 0.2
phases:
    build:
        commands:
            - sudo docker build -f Dockerfile-ubuntu-empty -t ubuntu-empty .
            - sudo docker tag ubuntu-empty 330996503740.dkr.ecr.us-east-1.amazonaws.com/udacity-cherkavi:ubuntu-empty-${TAG_PREFIX}
            - sudo docker push 330996503740.dkr.ecr.us-east-1.amazonaws.com/udacity-cherkavi:ubuntu-empty-${TAG_PREFIX}

